### ISSUE TITLE
 No such file or directory: 'simulation.json'

### ISSUE THREAD

**Issue by ghost** [pestadieu/OBDSimulator#1]
I encountered an error while running `python3 src/main.py`
I'm running on Ubuntu 20.04, Python3.8
Here is the traceback:

`Traceback (most recent call last):
  File "src/main.py", line 9, in <module>
    s.listen("vcan0")
  File "/home/joko/gits/OBDSimulator/src/can_server.py", line 125, in listen
    it = inputThread()
  File "/home/joko/gits/OBDSimulator/src/can_server.py", line 111, in __init__
    self.simulation = Simulation('simulation.json') 
  File "/home/joko/gits/OBDSimulator/src/can_server.py", line 29, in __init__
    with open(filename, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'simulation.json'`

**Comment by Taknok** [comment]
Do you have a `simulation.json` file in the same directory ?
